import { PDFDocument, rgb, StandardFonts, type PDFFont, type PDFPage } from "pdf-lib";
import type { ScanResult, Violation } from "./types";
import { metaFor, severityColor } from "./violation-meta";

type RGB = ReturnType<typeof rgb>;

const SURFACE = rgb(0.078, 0.098, 0.145);
const TEXT = rgb(0.9, 0.918, 0.949);
const MUTED = rgb(0.541, 0.58, 0.659);
const PASS = rgb(0.239, 0.863, 0.518);
function hexRgb(hex: string): RGB { const c = parseInt(hex.slice(1), 16); return rgb(((c >> 16) & 0xff) / 255, ((c >> 8) & 0xff) / 255, (c & 0xff) / 255); }

function esc(s: string): string {
  if (typeof s !== "string") return "";
  return s.replace(/[<>]/g, "");
}

/**
 * Generates PDF report for scan result using pdf-lib.
 *
 * Why: Creates multi-page PDF with header, accessibility score, violation breakdown,
 * and per-violation details. Auto-adds pages when content exceeds page height.
 *
 * @param result - Scan result containing score, violations, and repo metadata.
 * @returns Uint8Array of PDF file bytes, ready for download or save.
 */
export async function generatePdfReport(result: ScanResult): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  let page = doc.addPage([595, 842]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const margin = 48;
  let y = 842 - margin;

  page.drawRectangle({ x: 0, y: 842 - 90, width: 595, height: 90, color: SURFACE });
  page.drawText("WCAG Compliance Report", { x: margin, y: 842 - 50, size: 18, font: bold, color: TEXT });
  page.drawText("Generated by equity", { x: margin, y: 842 - 68, size: 10, font, color: MUTED });
  page.drawText(`Repo: ${esc(result.repoUrl)}`, { x: margin, y: 842 - 82, size: 9, font, color: MUTED });
  y = 842 - 120;

  const score = result.score;
  if (score) {
    page.drawText("Accessibility Score", { x: margin, y, size: 12, font: bold, color: TEXT });
    page.drawText(`${score.grade}  (${score.score}/100 — ${score.label})`, { x: margin, y: y - 18, size: 14, font: bold, color: PASS });
    page.drawText(`${score.totalViolations} violations across ${score.affectedFiles.length} files`, { x: margin, y: y - 38, size: 10, font, color: MUTED });
    y -= 64;

    page.drawText("Breakdown", { x: margin, y, size: 11, font: bold, color: TEXT });
    y -= 18;
    for (const b of score.breakdown) {
      page.drawText(`• ${esc(b.type.replace(/-/g, " "))}  x${b.count}`, { x: margin + 10, y, size: 9, font, color: MUTED });
      y -= 14;
    }
    y -= 10;
  }

  page.drawText("Violations", { x: margin, y, size: 13, font: bold, color: TEXT });
  y -= 20;

  const lineH = 15;
  const violations = result.violations || [];
  for (let i = 0; i < violations.length; i++) {
    const v = violations[i];
    const m = metaFor(v.type);
    const sev = { label: m.severity.charAt(0).toUpperCase() + m.severity.slice(1), color: hexRgb(severityColor(m.severity)) };
    if (y < margin + 40) {
      const np = doc.addPage([595, 842]);
      y = 842 - margin;
      drawViolation(np, margin, y, i, v, sev, font, bold, MUTED, TEXT, esc);
      y -= lineH * 3;
      page = np;
      continue;
    }
    drawViolation(page, margin, y, i, v, sev, font, bold, MUTED, TEXT, esc);
    y -= lineH * 3;
  }

  const bytes = await doc.save();
  return bytes;
}

function drawViolation(
  page: PDFPage, x: number, y: number, i: number,
  v: Violation,
  sev: { label: string; color: RGB },
  font: PDFFont, bold: PDFFont, muted: RGB, text: RGB, esc: (s: string) => string
) {
  page.drawText(`${i + 1}. [${sev.label}] ${esc(v.type)}`, { x, y, size: 10, font: bold, color: sev.color });
  page.drawText(`${esc(v.file)}:${v.line}`, { x: x + 320, y, size: 8, font, color: muted });
  page.drawText(esc(v.description).slice(0, 95), { x: x + 10, y: y - 13, size: 8, font, color: muted });
  page.drawText("—", { x, y: y - 26, size: 6, color: text });
}
