import type { ScoreResult, Violation, ScreenReaderOutput } from "./types";
import { metaFor, severityColor } from "./violation-meta";

interface ReportInput {
  repoUrl: string;
  score: ScoreResult;
  violations: Violation[];
  screenReader: ScreenReaderOutput[];
}

function escapeHtml(s: string): string {
  if (typeof s !== "string") return "";
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/**
 * Generates full WCAG compliance report as HTML string.
 *
 * Why: Produces standalone HTML page with score card, violation table, and screen reader diffs.
 * Uses severity coloring and WCAG reference mapping for each violation type.
 *
 * @param input - Report inputs: repo URL, score result, violations array, screen reader outputs.
 * @returns Complete HTML document string ready for browser rendering or file save.
 */
export function generateReport(input: ReportInput): string {
  const { repoUrl, score, violations, screenReader } = input;
  const date = new Date().toISOString().split("T")[0];

  const rows = violations.map((v, i) => {
    const m = metaFor(v.type);
    const sev = { label: m.severity.charAt(0).toUpperCase() + m.severity.slice(1), color: severityColor(m.severity), wcag: m.wcagRef.replace("WCAG ", "") };
    const sr = screenReader?.[i];
    return `
    <tr>
      <td style="color:${sev.color};font-weight:600">${sev.label}</td>
      <td><code>${escapeHtml(v.type)}</code></td>
      <td><code>${escapeHtml(v.file)}:${v.line}</code></td>
      <td>${escapeHtml(v.description)}</td>
      <td style="color:#6b7280">${sev.wcag}</td>
      <td>${sr ? escapeHtml(sr.current) : "—"}</td>
      <td style="color:#15803d">${sr ? escapeHtml(sr.fixed) : "—"}</td>
    </tr>`;
  }).join("");

  const breakdown = (score.breakdown || [])
    .map((b) => `<span class="chip">${escapeHtml(b.type.replace(/-/g, " "))} <b>×${b.count}</b></span>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WCAG Compliance Report — ${escapeHtml(repoUrl)}</title>
<style>
  :root { --ink:#0b0e14; --surface:#141925; --border:#243047; --text:#e6eaf2; --muted:#8a94a8; --pass:#3ddc84; --fail:#ff5c7a; --accent:#5b8cff; }
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: "Inter", system-ui, sans-serif; color: var(--text); background: var(--ink); padding: 48px 24px; line-height:1.5; }
  .wrap { max-width: 980px; margin: 0 auto; }
  header { display:flex; align-items:center; gap:14px; margin-bottom:8px; }
  .logo { width:40px; height:40px; border-radius:10px; background:var(--pass); color:var(--ink); display:grid; place-items:center; font-weight:800; font-family:"Space Grotesk",sans-serif; }
  h1 { font-family:"Space Grotesk",sans-serif; font-size:26px; }
  .sub { color:var(--muted); font-size:13px; margin-bottom:32px; }
  .score-card { display:flex; align-items:center; gap:28px; padding:28px; border:1px solid var(--border); border-radius:16px; background:var(--surface); margin-bottom:20px; }
  .grade { font-size:72px; font-weight:800; line-height:1; font-family:"Space Grotesk",sans-serif; border:3px solid ${score.color}; color:${score.color}; border-radius:18px; width:120px; height:120px; display:grid; place-items:center; }
  .meta h2 { font-size:19px; margin-bottom:6px; }
  .meta p { color:var(--muted); font-size:13px; }
  .chip { display:inline-block; background:var(--ink); border:1px solid var(--border); border-radius:999px; padding:4px 10px; font-size:11px; margin:3px 3px 0 0; color:var(--muted); }
  .chip b { color:var(--fail); }
  h3 { font-family:"Space Grotesk",sans-serif; font-size:17px; margin:32px 0 12px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th { text-align:left; padding:10px 12px; border-bottom:2px solid var(--border); font-size:11px; text-transform:uppercase; letter-spacing:.05em; color:var(--muted); }
  td { padding:10px 12px; border-bottom:1px solid var(--border); vertical-align:top; }
  tr:nth-child(even) { background:rgba(255,255,255,.02); }
  code { font-family:"JetBrains Mono",monospace; font-size:12px; color:#9ff0c2; }
  .footer { margin-top:44px; padding-top:16px; border-top:1px solid var(--border); font-size:11px; color:var(--muted); text-align:center; }
  @media print { body { background:#fff; color:#111; } .score-card,table { break-inside:avoid; } code { color:#0a7d3b; } }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="logo">A</div>
    <div><h1>WCAG Accessibility Compliance Report</h1></div>
  </header>
  <p class="sub">Generated by equity — ${date} · Repo: ${escapeHtml(repoUrl)}</p>

  <div class="score-card">
    <div class="grade">${score.grade}</div>
    <div class="meta">
      <h2>Accessibility Score: ${score.score}/100 (${score.label})</h2>
      <p>${score.totalViolations} violations across ${score.affectedFiles.length} files</p>
      <div style="margin-top:10px">${breakdown}</div>
    </div>
  </div>

  <h3>Violation Breakdown</h3>
  <table>
    <thead><tr><th>Severity</th><th>Type</th><th>Location</th><th>Description</th><th>WCAG</th><th>Screen Reader (now)</th><th>Fixed</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">equity — Built with Codex + GPT-5.6 — OpenAI Build Week 2026</div>
</div>
</body>
</html>`;
}
